# Generated by Django 3.1.7 on 2021-03-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ent_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
