# Generated by Django 3.1.7 on 2021-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0002_auto_20210326_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coorlat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='coorlng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
