# Generated by Django 3.1.7 on 2021-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0003_auto_20210327_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='certifier',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='competences',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
