# Generated by Django 3.1.7 on 2021-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0004_auto_20210407_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fourth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
