# Generated by Django 3.1.7 on 2021-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0005_auto_20210408_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fourth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
