# Generated by Django 3.1.7 on 2021-04-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0006_auto_20210408_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('nb_users', models.IntegerField()),
                ('competences', models.TextField(blank=True, max_length=500, null=True)),
                ('about_job', models.TextField(blank=True, max_length=500, null=True)),
                ('horaire', models.TimeField()),
                ('type_job', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alldone.users')),
            ],
        ),
    ]
