# Generated by Django 3.1.7 on 2021-04-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alldone', '0007_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alldone.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alldone.users')),
            ],
        ),
    ]
